const newsOptions = [
	{ key: 'abc-news', value: 'abc-news', text: 'ABC News'},
	{ key: 'axios', value: 'axios', text: 'Axios'},
	{ key: 'bbc', value: 'bbc-news', text: 'BBC'},
	{ key: 'bleacher-report', value: 'bleacher-report', text: 'Bleacher Report'},
	{ key: 'bloomberg', value: 'bloomberg', text: 'Bloomberg'},
	{ key: 'cbs-news', value: 'cbs-news', text: 'CBS News'},
	{ key: 'cnbc', value: 'cnbc', text: 'CNBC'},
	{ key: 'daily-mail', value: 'daily-mail', text: 'Daily Mail'},
	{ key: 'fortune', value: 'fortune', text: 'Fortune'},
	{ key: 'fox-news', value: 'fox-news', text: 'Fox News'},
	{ key: 'google-news', value: 'google-news', text: 'Google News'},
	{ key: 'hacker-news', value: 'hacker-news', text: 'HackerNews'},
	{ key: 'independent', value: 'independent', text: 'Independent'},
	{ key: 'le-monde', value: 'le-monde', text: 'Le Monde'},
	{ key: 'msnbc', value: 'msnbc', text: 'MSNBC'},
	{ key: 'mtv-news', value: 'mtv-news', text: 'MTV News'},
	{ key: 'national-geographic', value: 'national-geographic', text: 'National Geographic'},
	{ key: 'nbc-news', value: 'nbc-news', text: 'NBC News'},
	{ key: 'new-york-magazine', value: 'new-york-magazine', text: 'New York Magazine'},
	{ key: 'politico', value: 'politico', text: 'Politico'},
	{ key: 'recode', value: 'recode', text: 'Recode'},
	{ key: 'reddit-r-all', value: 'reddit-r-all', text: 'Reddit'},
	{ key: 'the-economist', value: 'the-economist', text: 'The Economist'},
	{ key: 'the-new-york-times', value: 'the-new-york-times', text: 'The New York Times'},
	{ key: 'the-wall-street-journal', value: 'the-wall-street-journal', text: 'The Wall Street Journal'},
	{ key: 'the-washington-post', value: 'the-washington-post', text: 'The Washington Post'},
	{ key: 'time', value: 'time', text: 'Time'},
	{ key: 'usa-today', value: 'usa-today', text: 'USA Today'},
	{ key: 'wired', value: 'wired', text: 'Wired'},
]

export default newsOptions